//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DongPhi
    {
        public int ID { get; set; }
        public string MaSoThue { get; set; }
        public string TenCongTy { get; set; }
        public string NguoiNhanPhieuThu { get; set; }
        public string Sdt { get; set; }
        public System.DateTime NgayChuyenTien { get; set; }
        public System.DateTime NgayGuiPhieuThu { get; set; }
        public decimal SoTienDong { get; set; }
        public string GhiChu { get; set; }
    }
}
