//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Vinasa.Validation;
namespace Vinasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOINGHIQUOCTE
    {
        public HOINGHIQUOCTE()
        {
            this.THAMGIAHOINGHIQUOCTEs = new HashSet<THAMGIAHOINGHIQUOCTE>();
        }
    
        public int ID { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [ICRequired(ErrorMessage = "Đã tồn tại hội nghị quốc tế này!")]
        public string Ten { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [StringRequired(ErrorMessage = "Vui lòng điền trường này!")]
        public string DiaDiem { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [DateTimeRequired(ErrorMessage = "Ngày diễn ra phải lớn hơn ngày hiện tại!")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime ThoiGianBatDau { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [EndDateTimeRequired("ThoiGianBatDau")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime ThoiGianKetThuc { get; set; }
    
        public virtual ICollection<THAMGIAHOINGHIQUOCTE> THAMGIAHOINGHIQUOCTEs { get; set; }
    }
}
