//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOINGHIQUOCTE
    {
        public HOINGHIQUOCTE()
        {
            this.THAMGIAHOINGHIQUOCTEs = new HashSet<THAMGIAHOINGHIQUOCTE>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string DiaDiem { get; set; }
        public System.DateTime ThoiGianBatDau { get; set; }
        public System.DateTime ThoiGianKetThuc { get; set; }
    
        public virtual ICollection<THAMGIAHOINGHIQUOCTE> THAMGIAHOINGHIQUOCTEs { get; set; }
    }
}
