//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOAHOC
    {
        public KHOAHOC()
        {
            this.THAMGIAKHOAHOCs = new HashSet<THAMGIAKHOAHOC>();
        }
    
        public int Id { get; set; }
        public string TenKhoaDaoTao { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string HinhThuc { get; set; }
    
        public virtual ICollection<THAMGIAKHOAHOC> THAMGIAKHOAHOCs { get; set; }
    }
}
