//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOINHANGIAITHUONG
    {
        public int Id { get; set; }
        public Nullable<int> GiaiThuongId { get; set; }
        public string MaSoThue { get; set; }
        public string TenDonVi { get; set; }
        public string TenNguoiDaiDienPhapLuat { get; set; }
        public string ChucDanh { get; set; }
        public string Email { get; set; }
        public string DiDong { get; set; }
        public string TenNguoiLienHeVoiBTC { get; set; }
        public string ChucDanhNguoiLienHe { get; set; }
        public string EmailNguoiLienHe { get; set; }
        public string DiDongNguoiLienHe { get; set; }
        public int ProvinceId { get; set; }
        public string DiaChi { get; set; }
        public string PhieuDangKy { get; set; }
    
        public virtual GIAITHUONG GIAITHUONG { get; set; }
    }
}
