//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seminar
    {
        public Seminar()
        {
            this.SeminarParticipants = new HashSet<SeminarParticipant>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime OpenDate { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedUtc { get; set; }
    
        public virtual ICollection<SeminarParticipant> SeminarParticipants { get; set; }
    }
}
