//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeminarParticipant
    {
        public int Id { get; set; }
        public Nullable<int> SeminarId { get; set; }
        public string Name { get; set; }
        public string TaxNumber { get; set; }
        public string Company { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public int ProvinceId { get; set; }
        public string JobTitle { get; set; }
        public string Operation { get; set; }
        public bool RegistrySeminar { get; set; }
        public bool RegistryBusinessMatching { get; set; }
        public bool RegistryExhibition { get; set; }
        public bool RegistryTicket { get; set; }
        public Nullable<System.DateTime> CreatedUtc { get; set; }
    
        public virtual Seminar Seminar { get; set; }
    }
}
