//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUDUNGDICHVUKHAC
    {
        public int ID { get; set; }
        public string MaSoThue { get; set; }
        public string TenCongTy { get; set; }
        public System.DateTime NgayBatDauHopDong { get; set; }
        public System.DateTime NgayKetThucHopDong { get; set; }
        public string TenDichVuKhac { get; set; }
        public int GiaGoc { get; set; }
        public int GiaUuDai { get; set; }
        public string ChiecKhauVinasa { get; set; }
        public string TenNguoiLienHe { get; set; }
        public string ChucDanh { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public string GhiChu { get; set; }
    }
}
