//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMGIAKHOAHOC
    {
        public int Id { get; set; }
        public string HoTen { get; set; }
        public string CongTyToChucCoQuan { get; set; }
        public string ChucDanh { get; set; }
        public string Email { get; set; }
        public string Sdt { get; set; }
        public int SoLuongHocVien { get; set; }
        public bool HoiVienVinasa { get; set; }
        public Nullable<int> IdKhoaHoc { get; set; }
    
        public virtual KHOAHOC KHOAHOC { get; set; }
    }
}
