//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Vinasa.Validation;
namespace Vinasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMGIAHOINGHIQUOCTE
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [StringRequired(ErrorMessage = "Vui lòng điền trường này!")]
        public string TenDonVi { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [StringRequired(ErrorMessage = "Vui lòng điền trường này!")]
        public string DonViChungToiLa { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [StringRequired(ErrorMessage = "Vui lòng điền trường này!")]
        public string DiaChi { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [StringRequired(ErrorMessage = "Vui lòng điền trường này!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{4})[-. ]?([0-9]{4})$", ErrorMessage = "Không hợp lệ")]
        public string DienThoai { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [StringRequired(ErrorMessage = "Vui lòng điền trường này!")]
        public string DaiDienLienHe { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [StringRequired(ErrorMessage = "Vui lòng điền trường này!")]
        public string ChucVu { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [StringRequired(ErrorMessage = "Vui lòng điền trường này!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Không hợp lệ")]
        public string DiDong { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        [StringRequired(ErrorMessage = "Vui lòng điền trường này!")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Không hợp lệ")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        public bool DangKyThamDu { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        public bool DangKyPhatBieu { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        public bool DangKyGianHangTrienLam { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        public bool DangKyBusinessMatchingOnline { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        public bool DangKyBusinessMatchingOffline { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        public bool DangKyTaiTro { get; set; }

        [Required(ErrorMessage = "Vui lòng điền trường này!")]
        public bool DangKyQuangCao { get; set; }
        public Nullable<int> HoiNghiQT_ID { get; set; }
    
        public virtual HOINGHIQUOCTE HOINGHIQUOCTE { get; set; }
    }
}
