// <auto-generated />
namespace Vinasa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Seminars3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seminars3));
        
        string IMigrationMetadata.Id
        {
            get { return "202206300705012_Seminars3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
